---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_macos: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# https://github.com/geerlingguy/ansible-role-dotfiles
dotfiles_repo: https://github.com/nickwaelkens/dotfiles.git
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dev/dotfiles
dotfiles_home: "~"
dotfiles_files:
  - .config/fish/config.fish
  - .config/fish/aliases.fish
  - .config/fish/path.fish
  - .config/fish/functions/mkcd.fish
  - .config/starship.toml
  - .gitignore
  - .gitconfig
  - .macos
  - .vimrc

homebrew_installed_packages:
  # Tools
  # - ansible # Installed via Pip.
  - ack
  - coreutils
  - fish
  - fnm
  - gnupg
  - grc
  - jump
  - libgit2
  - node
  - nvim
  - openssl
  - pinentry-mac
  - readline
  - rename
  - roundup
  - starship
  - svn  # Required for fonts
  - wget
  - yarn
  # More recent versions of macOS tools
  - curl
  - git
  - grep
  - nano

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # Applications
  - 1password
  - docker
  - dozer
  - dropbox
  - firefox
  - google-chrome
  - insomnia
  - iterm2
  - kap
  - keepingyouawake
  - keka
  - lulu
  - macdown
  - ngrok
  - notion
  - postico
  - puush
  - raycast
  - rectangle
  - sequel-pro
  - slack
  - sourcetree
  - spotify
  - sublime-text
  - sensiblesidebuttons
  - transmission
  - telegram
  - visual-studio-code
  - vlc
  - webstorm
  - whatsapp
  - zoom
  # Screensavers
  - aerial
  - brooklyn
  # Fonts
  - font-fira-code-nerd-font
  - font-hack
  - font-inter
  - font-jetbrains-mono-nerd-font
  - font-lato
  - font-open-sans
  - font-source-code-pro
  - font-source-sans-pro
  - font-source-serif-pro
  - font-roboto
  - font-roboto-mono

# See `geerlingguy.mas` role documentation for usage instructions.
# mas_installed_apps:
#  - { id: 1502839586, name: "Hand Mirror" }
mas_email: ""
mas_password: ""

macos_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages: []
npm_packages: []
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
