---
# Custom iTerm2 theme.
- name: Ensure iTerm2 "Solarized Dark" theme is added.
  copy:
    src: files/terminal/schemes
    dest: ~/.config/iterm2

- name: Run script that properly installs the scheme(s) I want to be using in iTerm2.
  # See https://github.com/mbadolato/iTerm2-Color-Schemes for documentation on how to use this import script.
  script: | # Run multi-line commands in Ansible.
    files/terminal/tools/import-scheme.sh 'schemes/Solarized Dark.itermcolors'

- name: Sync iTerm preferences.
  shell: |
    # Specify the preferences directory
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "{{ playbook_dir }}/files/terminal"
    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true